<div class="clearfix">
	<div class="col-md-6">
		<strong><?php echo $this->__('Select a territory to attack from'); ?></strong>
		<select class="form-control" name="from"></select>
	</div>
	<div class="col-md-6">
		<strong><?php echo $this->__('Select a territory to attack'); ?></strong>
		<select class="form-control" name="to"></select>
	</div>
</div>
<div class="clearfix">
	<div class="col-md-6">
		<strong><?php echo $this->__('Enter the number of units to attack with'); ?></strong>
		<div class="input-group">
			<div class="input-group-addon">
<?php	$this->includeTemplate('unit_icon'); ?>
			</div>
			<input class="form-control" type="number" name="attack" value="3" min="1" placeholder="<?php echo $this->__('Enter the number of units to attack with'); ?>" required />
		</div>
	</div>
	<div class="col-md-6">
		<div data-value="move">
			<strong><?php echo $this->__('Enter the number of units to move with'); ?></strong>
			<div class="input-group">
				<div class="input-group-addon">
<?php	$this->includeTemplate('unit_icon'); ?>
				</div>
				<input class="form-control" type="number" name="move" value="1" min="1" placeholder="<?php echo $this->__('Enter the number of units to move with'); ?>" required />
			</div>
		</div>
	</div>
</div>