<section>
	<h1><?php echo $this->__('Games'); ?></h1>
<?php
	if(empty($games)) {
?>
	<div class="jumbotron">
		<p class="text-info"><span class="glyphicon glyphicon-info-sign"></span> <?php echo $this->__('There are no games available at this time.'); ?></p>
	</div>
<?php
	} else {
?>
	<table id="gamelist" class="table table-striped table-hover">
		<thead>
			<tr><th><?php echo $this->__('Name'); ?></th><th><?php echo $this->__('Map'); ?></th><th><?php echo $this->__('Players'); ?></th><th><?php echo $this->__('Host'); ?></th></tr>
		</thead>
		<tbody>
<?php
		foreach($games as $game) {
			$map = $game->getMap();
			$startedEndedLocked = '';
			if($game->hasStarted()) {
				$startedEndedLocked = 'started';
			} else if($game->hasEnded()) {
				$startedEndedLocked = 'ended';
			}
			if($game->hasPassword()) {
				$startedEndedLocked .= ' password';
			}
?>
			<tr class="<?php echo $startedEndedLocked; ?>">
				<td><a href="<?php echo \imperator\page\Game::getURL($game); ?>"><?php echo $game->getName(); ?></a></td>
				<td><a href="<?php echo \imperator\page\Map::getURL($map); ?>"><?php echo $this->__($map->getName()); ?></a></td>
				<td><?php echo $this->__('%1$d / %2$d', $game->getNumberOfPlayers(), $map->getPlayers()); ?></td>
				<td><?php echo \imperator\page\DefaultPage::getProfileLink($game->getOwner()->getUser()); ?></td>
			</tr>
<?php
		}
?>
		</tbody>
	</table>
<?php
	}
?>
</section>
<?php
	$chat->execute(true);
?>