<section>
	<h1><?php echo $game->getName(); ?></h1>
	<h4><?php echo $this->__('Map'); ?></h4>
	<p><a href="<?php echo \imperator\page\Map::getURL($game->getMap()); ?>"><?php echo $this->__($game->getMap()->getName()); ?></a></p>
	<table class="table">
		<thead>
			<tr><th><?php echo $this->__('Player'); ?></th><th><?php echo $this->__('Mission'); ?></th></tr>
		</thead>
		<tbody>
<?php
	foreach($game->getPlayers() as $player) {
?>
<tr>
	<td><?php echo \imperator\page\DefaultPage::getProfileLink($player), ($game->getOwner() == $player ? ' '.$this->__('Owner') : '' ), ($player->getState() == \imperator\game\Player::STATE_VICTORIOUS ? ' '.$this->__('(Winner)') : ''); ?></td>
	<td><strong><?php echo $player->getMission()->getName(); ?></strong><p><?php echo $player->getMission()->getDescription($language); ?></p></td>
</tr>
<?php	} ?>
		</tbody>
	</table>
</section>
<?php
	if($chat) {
		$chat->execute(true);
	}
?>