<nav>
	<ul class="nav nav-tabs nav-justified">
		<li style="display: none;"><a href="#tab-territory"></a></li>
		<li class="active"><a href="#tab-players"><?php echo $this->__('Players'); ?></a></li>
		<li><a href="#tab-territories"><?php echo $this->__('Territories'); ?></a></li>
		<li><a href="#tab-regions"><?php echo $this->__('Regions'); ?></a></li>
		<li class="player-only"><a href="#tab-cards"><?php echo $this->__('Cards'); ?></a></li>
		<li class="player-only"><a href="#tab-chatbox"><?php echo $this->__('Chat'); ?><span class="number"></span></a></li>
		<li><a href="#tab-log"><?php echo $this->__('Combat Log'); ?><span class="number"></span></a></li>
		<li><a href="#tab-settings"><?php echo $this->__('Settings'); ?></a></li>
		<li class="mobile-only"><a href="#tab-map"><?php echo $this->__('Map'); ?></a></li>
	</ul>
</nav>
<div class="row swipe-panes">
	<div class="col-sm-6">
		<section id="territory" class="swipe-pane">
			<h2><img data-value="flag" src="" alt="" /> <span data-value="name">---</span></h2>
			<table class="table">
				<thead>
					<tr>
						<th><?php echo $this->__('Player'); ?></th>
						<th><?php echo $this->__('Units'); ?></th>
						<th><?php echo $this->__('Regions'); ?></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td data-value="owner"></td>
						<td data-value="units"></td>
						<td data-value="regions"></td>
					</tr>
				</tbody>
			</table>
			<h3><?php echo $this->__('Borders'); ?></h3>
			<div data-value="borders">
				<div class="row" data-value="border">
					<div class="col-xs-1"><img data-value="border-flag" src="" alt="" /></div>
					<div class="col-xs-11"><a href="" data-value="border-name"></a></div>
				</div>
			</div>
		</section>
		<section id="players" class="swipe-pane active">
			<table class="table">
				<thead>
					<tr>
						<th><?php echo $this->__('Player'); ?></th>
						<th><?php echo $this->__('Territories'); ?></th>
						<th><?php echo $this->__('Units'); ?></th>
						<th><?php echo $this->__('Units per turn'); ?></th>
					</tr>
				</thead>
				<tbody>
<?php	foreach($game->getPlayers() as $player) { ?>
					<tr data-player="<?php echo $player->getId(); ?>">
						<td data-value="name"><?php echo \imperator\page\DefaultPage::getProfileLink($player); ?></td>
						<td data-value="territories">-</td>
						<td data-value="units">-</td>
						<td>
							<span data-value="unitsperturn"></span>
							(<span data-value="unitsperturn-regions" title="<?php echo $this->__('Units gained from regions'); ?>"></span>
							+
							<span data-value="unitsperturn-territories" title="<?php echo $this->__('Units gained from territories'); ?>"></span>)
						</td>
					</tr>
<?php	} ?>
				</tbody>
			</table>
			<div class="player-only">
				<h2 data-value="mission-name"></h2>
				<p data-value="mission-description"></p>
			</div>
		</section>
		<section id="territories" class="swipe-pane">
			<table class="table">
				<thead>
					<tr>
						<th><?php echo $this->__('Flag'); ?></th>
						<th><?php echo $this->__('Territory'); ?></th>
						<th><?php echo $this->__('Player'); ?></th>
						<th><?php echo $this->__('Units'); ?></th>
						<th><?php echo $this->__('Regions'); ?></th>
					</tr>
				</thead>
				<tbody>
<?php	foreach($game->getMap()->getTerritories() as $territory) { ?>
					<tr data-territory="<?php echo $territory->getId(); ?>">
						<td>
							<img src="<?php echo \imperator\page\Game::getTerritoryFlag($territory); ?>" alt="<?php echo $this->__('Flag of %1$s', $territory->getName()); ?>" data-value="flag" />
						</td>
						<td>
							<a href="#tab-territory-<?php echo $territory->getId(); ?>"><?php echo $this->__($territory->getName()); ?></a>
						</td>
						<td>
							<?php echo \imperator\page\DefaultPage::getProfileLink($territory->getOwner()); ?>
						</td>
						<td>
							<?php echo $territory->getUnits(); ?>
						</td>
						<td data-value="regions">
	<?php	foreach($territory->getRegions() as $region) { ?>
							<img src="<?php echo \imperator\page\Game::getRegionFlag($region); ?>" alt="<?php echo $this->__($region->getName()); ?>" />
	<?php	} ?>
						</td>
					</tr>
<?php	} ?>
				</tbody>
			</table>
		</section>
		<section id="regions" class="swipe-pane">
<?php	foreach($game->getMap()->getRegions() as $region) { ?>
			<h2>
				<img src="<?php echo \imperator\page\Game::getRegionFlag($region); ?>" alt="" /> <?php echo $this->__($region->getName()); ?>
				<button data-toggle="collapse" data-target="#region-<?php echo $this->__($region->getId()); ?>" class="btn collapsed">
					<span class="glyphicon glyphicon-chevron-up"></span>
					<span class="glyphicon glyphicon-chevron-down"></span>
				</button>
				<button class="btn" data-button="highlight" data-region="<?php echo $this->__($region->getId()); ?>"><?php echo $this->__('Highlight'); ?></button>
			</h2>
			<p><?php echo $this->__('%1$d territories, %2$d units per turn', count($region->getTerritories()), $region->getUnitsPerTurn()); ?></p>
			<div class="region-division" data-region="<?php echo $this->__($region->getId()); ?>"></div>
			<div id="region-<?php echo $this->__($region->getId()); ?>" class="collapse">
	<?php	foreach($region->getTerritories() as $territory) { ?>
				<div class="row" data-territory="<?php echo $territory->getId(); ?>">
					<div class="col-xs-1">
						<img src="<?php echo \imperator\page\Game::getTerritoryFlag($territory); ?>" alt="" />
					</div>
					<div class="col-xs-11">
						<a href="#tab-territory-<?php echo $territory->getId(); ?>" style="color: #<?php echo $territory->getOwner()->getColor(); ?>;"><?php echo $this->__($territory->getName()); ?></a>
					</div>
				</div>
	<?php	} ?>
			</div>
<?php	} ?>
		</section>
		<section id="cards" class="swipe-pane player-only">
			<div data-value="card-list" class="text-center">
<?php
	if($cards) {
		$cards->execute(true);
	}
?>
			</div>
			<div id="card-controls">
				<button class="btn btn-success" data-button="cards" data-value="4"><?php echo $this->__('Place %1$d units', 4); ?></button>
				<button class="btn btn-success" data-button="cards" data-value="6"><?php echo $this->__('Place %1$d units', 6); ?></button>
				<button class="btn btn-success" data-button="cards" data-value="8"><?php echo $this->__('Place %1$d units', 8); ?></button>
				<button class="btn btn-success" data-button="cards" data-value="10"><?php echo $this->__('Place %1$d units', 10); ?></button>
			</div>
		</section>
		<section id="chatbox" class="swipe-pane player-only">
<?php
	if($chat) {
		$chat->execute(true);
	}
?>
		</section>
		<section id="log" class="swipe-pane">
			Combat Log
		</section>
		<section id="settings" class="swipe-pane">
			<label>
				<input type="checkbox" name="autoroll" />
				<?php echo $this->__('Autoroll'); ?>
			</label>
			<p>{$autorolldesc}</p>
			<hr />
			<label>
				<input type="radio" name="unitgraphics" value="default" />
				<?php echo $this->__('Default unit graphics'); ?>
			</label>
			<p><?php echo $this->__('Select this to use unit icons.'); ?></p>
			<label>
				<input type="radio" name="unitgraphics" value="numeric" />
				<?php echo $this->__('Numeric unit graphics'); ?>
			</label>
			<p><?php echo $this->__('Select this to use unit numbers.'); ?></p>
			<label>
				<input type="radio" name="unitgraphics" value="none" />
				<?php echo $this->__('No unit graphics'); ?>
			</label>
			<p><?php echo $this->__('Select this to disable units.'); ?></p>
		</section>
	</div><!--
	--><div class="col-sm-6">
		<section id="map" class="swipe-pane active">
			<div class="map-square">
				<div class="map-controls">
					<button class="btn btn-default zoom-in" title="<?php echo $this->__('Zoom in'); ?>">+</button>
					<button class="btn btn-default zoom-out" title="<?php echo $this->__('Zoom out'); ?>">-</button>
				</div>
				<div class="map-container">
					<img src="<?php echo $mapurl; ?>" alt="<?php echo $this->__('Map of %1$s', $game->getMap()->getName()); ?>" data-unit-graphics="<?php echo $unitgraphics; ?>" />
				</div>
			</div>
		</section>
	</div>
</div>
<div id="turn-controls">
	<button class="btn btn-default collapsed" data-toggle="collapse" data-target="#controls-box">
		<span class="glyphicon glyphicon-chevron-up"></span>
		<span class="glyphicon glyphicon-chevron-down"></span>
	</button>
	<div class="collapse container-fluid" id="controls-box">
		<?php echo $this->__('%1$s\'s turn', \imperator\page\DefaultPage::getProfileLink($game->getCurrentPlayer())); ?>
		<button class="btn btn-default player-only" data-value="units-left-fortify" disabled title="<?php echo $this->__('Number of units left to place'); ?>"><span class="number">0</span></button>
		<button class="btn btn-default player-only" data-value="units-left-move" disabled title="<?php echo $this->__('Number of units left to move'); ?>"><span class="number">0</span></button>
		<button class="btn btn-primary player-only" data-button="stack" title="<?php echo $this->__('Place new units instead of attacking'); ?>"><?php echo $this->__('Stack'); ?> <span class="number">0</span></button>
		<button class="btn btn-warning player-only" data-button="move" title="><?php echo $this->__('Stop attacking and start moving units'); ?>"><?php echo $this->__('Move'); ?></button>
		<button class="btn btn-warning player-only" data-button="endturn" title="<?php echo $this->__('Cede control and end your turn'); ?>"><?php echo $this->__('End turn'); ?></button>
		<button class="btn btn-danger player-only pull-right" data-button="forfeit" title="<?php echo $this->__('Surrender the game'); ?>"><?php echo $this->__('Forfeit'); ?></button>
	</div>
</div>
<div id="radial-menu">
	<svg version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 150 150">
		<defs>
			<path d="M 0 125 Q 0 25 75 25 V 0 L 125 50 75 100 V 75 Q 25 75 0 125 Z" fill="lime" id="pattern-img-arrow-green" />
			<path d="M 0 125 Q 0 25 75 25 V 0 L 125 50 75 100 V 75 Q 25 75 0 125 Z" fill="red" id="pattern-img-arrow-red" />
			<pattern viewBox="0 0 125 125" height="1" width="1" id="pattern-arrow-green">
				<use xlink:href="#pattern-img-arrow-green" />
			</pattern>
			<pattern viewBox="0 0 125 125" height="1" width="1" id="pattern-arrow-red">
				<use xlink:href="#pattern-img-arrow-red" />
			</pattern>
		</defs>
		<circle class="outer" r="50" cy="75" cx="75" />
		<circle class="inner" r="20" cy="75" cx="75" />
		<g data-button="move-from" title="<?php echo $this->__('Move units from this territory'); ?>">
			<path class="slice" d="M 81.18 94.021 L 90.451 122.553 A 50 50 0 0 0 125 75 L 95 75 A 20 20 0 0 1 81.18 94.021 Z" />
			<rect height="30" width="30" fill="url(#pattern-units-1)" x="88.316" y="80.572" />
			<rect height="13" width="13" y="82" x="108" fill="url(#pattern-arrow-green)" />
		</g>
		<g data-button="move-to" title="<?php echo $this->__('Move units to this territory'); ?>">
			<path class="slice" d="M 58.82 86.756 L 34.549 104.389 A 50 50 0 0 0 90.451 122.553 L 81.18 94.021 A 20 20 0 0 1 58.82 86.756 Z" />
			<rect height="30" width="30" fill="url(#pattern-units-1)" x="49.184" y="93.287" />
			<rect height="13" width="13" y="97" x="50" transform="rotate(90, 57.5, 102.5)" fill="url(#pattern-arrow-green)" />
		</g>
		<g data-button="stack" title="<?php echo $this->__('Fortify this territory'); ?>">
			<path class="slice" d="M 58.82 63.244 L 34.549 45.611 A 50 50 0 0 0 34.549 104.389 L 58.82 86.756 A 20 20 0 0 1 58.82 63.244 Z" />
			<rect height="30" width="30" fill="url(#pattern-units-1)" x="25" y="60" />
			<path d="M47 60 h 3 v 5 h 5 v 3 h -5 v 5 h -3 v -5 h -5 v -3 h 5 Z" fill="lime" />
		</g>
		<g data-button="attack-to" title="<?php echo $this->__('Attack this territory'); ?>">
			<path class="slice" d="M 81.18 55.979 L 90.451 27.447 A 50 50 0 0 0 34.549 45.611 L 58.82 63.244 A 20 20 0 0 1 81.18 55.979 Z" />
			<rect height="30" width="30" fill="url(#pattern-units-1)" x="49.184" y="26.713" />
			<rect height="13" width="13" y="30" x="50" transform="rotate(90, 57.5, 37.5)" fill="url(#pattern-arrow-red)" />
		</g>
		<g data-button="attack-from" title="<?php echo $this->__('Attack from this territory'); ?>">
			<path class="slice" d="M 95 75 L 125 75 A 50 50 0 0 0 90.451 27.447 L 81.18 55.979 A 20 20 0 0 1 95 75 Z" />
			<rect height="30" width="30" fill="url(#pattern-units-1)" x="88.316" y="39.428" />
			<rect height="13" width="13" y="44" x="105" fill="url(#pattern-arrow-red)" />
		</g>
	</svg>
</div>