<section>
	<h1><?php echo $this->__($map->getName()); ?></h1>
	<div class="row">
		<div class="col-md-6">
			<div id="description">
				<?php echo $this->__($map->getDescription($language->getHtmlLang())); ?>
			</div>
			<div id="regions">
				<h2><?php echo $this->__('Regions'); ?></h2>
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th><?php echo $this->__('Region'); ?></th><th><?php echo $this->__('Units per turn'); ?></th><th><?php echo $this->__('Number of territories'); ?></th>
						</tr>
					</thead>
					<tbody>
<?php	foreach($map->getRegions() as $region) { ?>
						<tr>
							<td>
								<img src="<?php echo \imperator\url\ImageURL::getRegionFlag($region); ?>" alt="" /> <?php echo $this->__($region->getName()); ?>
							</td>
							<td><?php echo $region->getUnitsPerTurn(); ?></td>
							<td><?php echo count($region->getTerritories()); ?></td>
						</tr>
<?php	} ?>
					</tbody>
				</table>
			</div>
			<div id="missions">
				<h2><?php echo $this->__('Missions'); ?></h2>
<?php	foreach($map->getMissions() as $mission) { ?>
				<h3><?php echo $mission->getName(); ?></h3>
				<p><?php echo $mission->getDescription($language); ?></p>
<?php	} ?>
			</div>
		</div>
		<div class="col-md-6">
			<noscript><p><?php echo $this->__('Javascript needs to be enabled to interact with this map.'); ?></p></noscript>
			<div id="map">
				<div class="map-square">
					<div class="map-controls">
						<button class="btn btn-default zoom-in" title="<?php echo $this->__('Zoom in'); ?>">+</button>
						<button class="btn btn-default zoom-out" title="<?php echo $this->__('Zoom out'); ?>">-</button>
					</div>
					<div class="map-container">
						<img src="<?php echo $mapurl; ?>" alt="<?php echo $this->__('Map of %1$s', $map->getName()); ?>" />
					</div>
					<div>
<?php	foreach($map->getTerritories() as $territory) { ?>
						<div class="territory-hover" data-territory="<?php echo $territory->getId(); ?>">
							<div class="flag" style="background-image: url('<?php echo \imperator\url\ImageURL::getTerritoryFlag($territory); ?>')"></div>
							<div class="content">
								<h4><?php echo $this->__($territory->getName()); ?></h4>
								<ul class="regions">
<?php	foreach($territory->getRegions() as $region) { ?>
<li>
	<span style="background-image: url('<?php echo \imperator\url\ImageURL::getRegionFlag($region); ?>')"></span>
	<?php echo $this->__($region->getName()); ?>
</li>
<?php	} ?>
								</ul>
							</div>
						</div>
<?php	} ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>