<section>
	<h1><?php echo $this->__('Maps'); ?></h1>
	<table id="maplist" class="table table-striped table-hover sortable">
		<thead>
			<tr><th><?php echo $this->__('Name'); ?></th><th><?php echo $this->__('Players'); ?></th></tr>
		</thead>
		<tbody>
<?php	foreach($maps as $map) { ?>
			<tr>
				<td><a href="<?php echo \imperator\page\Map::getURL($map); ?>"><?php echo $this->__($map->getName()); ?></a></td>
				<td><?php echo $map->getPlayers(); ?></td>
			</tr>
<?php	} ?>
		</tbody>
	</table>
</section>