<!DOCTYPE html>
<html lang="<?php echo $language->getHtmlLang(); ?>" dir="<?php echo $language->getTextDirection(); ?>">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no" />
	<title><?php echo $this->__('Imperator | %1$s', $title); ?></title>
	<link href="<?php echo new \imperator\url\ImageURL('favicon.png'); ?>" type="image/png" rel="shortcut icon" />
	<script src="<?php echo new \imperator\url\JavascriptURL('jquery-2.1.3.min.js'); ?>"></script>
	<script src="<?php echo new \imperator\url\JavascriptURL('bootstrap.min.js'); ?>"></script>
	<link href="<?php echo new \imperator\url\CssURL('bootstrap.min.css'); ?>" type="text/css" rel="stylesheet" />
	<link href="<?php echo new \imperator\url\CssURL('style.css'); ?>" type="text/css" rel="stylesheet" />
	<script>//<![CDATA[
<?php echo $javascriptSettings; ?>
	//]]></script>
<?php
	foreach($css as $file) {
		echo '<link href="', new \imperator\url\CssURL($file), '" type="text/css" rel="stylesheet" />', "\n";
	}
	foreach($javascript as $file) {
		echo '<script src="', new \imperator\url\JavascriptURL($file), '"></script>', "\n";
	}
?>
</head>
<body>
<?php
	$this->includeTemplate('header');
?>
<div id="main" class="<?php echo $mainClass; ?>">
	<div id="content">
<?php
	$body->execute(true);
?>
	</div>
<?php
	echo $footer;
?>
</div>
</body>
</html>